apiVersion: v1
kind: Service
metadata:
  name: di-bd-service-service-{{ .Values.image.branch }}
  labels:
    app.kubernetes.io/name: "di-bd-service"  
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service  }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"  
spec:
  type: NodePort
  selector:
    app: di-bd-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
