apiVersion: v1
kind: Service
metadata:
  name: di-frontend-service-{{ .Values.image.tag }}
  labels:
    app.kubernetes.io/name: "di-frontend"  
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service  }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"  
spec:
  type: NodePort
  selector:
    app: di-frontend-{{ .Values.image.tag }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
