kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "sandbox-test-ingress-{{ .Values.image.tag }}"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}

spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: sandbox-test-service-{{ .Values.image.tag }}
              servicePort: 80
