apiVersion: v1
kind: Service
metadata:
  name: di_bd_service-service-{{ .Values.image.branch }}
  labels:
    app.kubernetes.io/name: "simple-java-service"  
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service  }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"  
spec:
  type: NodePort
  selector:
    app: di_bd_service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
